version: 2

project_name: Werunos

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: werunos
    binary: werunos
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-IC:/PROGRA~2/WinFsp/inc/fuse
      - CGO_LDFLAGS=-LC:/PROGRA~2/WinFsp/lib -lwinfsp-x64
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    
archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

scoops:
  - name: werunos
    repository:
      owner: NilayShenai
      name: scoop-bucket
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: goonix Developer
      email: nilayshenai@gmail.com
    homepage: "https://github.com/NilayShenai/Werunos"
    description: "Lightweight userspace Ext4 & Btrfs filesystem driver for Windows via WinFsp."
    license: MIT

